name: spacetoday_crawler
description: A new Flutter package.
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+4
  dio: ^3.0.10

dev_dependencies:
  test: ^1.15.4
  mockito: ^4.1.3